// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smarthomeAPI.Data;

#nullable disable

namespace smarthomeAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230312184528_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("smarthomeAPI.Models.EnvironmentType", b =>
                {
                    b.Property<int>("EnvironmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnvironmentId"));

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ParentEnvironmentID")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EnvironmentId");

                    b.HasIndex("UserId", "ParentEnvironmentID");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("smarthomeAPI.Models.RawData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EnvironmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<float>("accelerometer_x")
                        .HasColumnType("real");

                    b.Property<float>("accelerometer_y")
                        .HasColumnType("real");

                    b.Property<float>("accelerometer_z")
                        .HasColumnType("real");

                    b.Property<float>("compass_x")
                        .HasColumnType("real");

                    b.Property<float>("compass_y")
                        .HasColumnType("real");

                    b.Property<float>("compass_z")
                        .HasColumnType("real");

                    b.Property<float>("gyroscope_x")
                        .HasColumnType("real");

                    b.Property<float>("gyroscope_y")
                        .HasColumnType("real");

                    b.Property<float>("gyroscope_z")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentID", "LoggedTime", "DeviceName");

                    b.ToTable("RawDatas");
                });

            modelBuilder.Entity("smarthomeAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("smarthomeAPI.Models.EnvironmentType", b =>
                {
                    b.HasOne("smarthomeAPI.Models.User", "User")
                        .WithMany("Environments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("smarthomeAPI.Models.RawData", b =>
                {
                    b.HasOne("smarthomeAPI.Models.EnvironmentType", "Environment")
                        .WithMany("RawDatas")
                        .HasForeignKey("EnvironmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("smarthomeAPI.Models.EnvironmentType", b =>
                {
                    b.Navigation("RawDatas");
                });

            modelBuilder.Entity("smarthomeAPI.Models.User", b =>
                {
                    b.Navigation("Environments");
                });
#pragma warning restore 612, 618
        }
    }
}
